server:
    port: 8081
spring:
    profiles:
        active: dev
---
server:
    port: 8082
spring:
    profiles: dev
---
server:
    port: 8083
spring:
    profiles: prod
#person:
#    lastName: zhangsan
#    age: 18
#    boss: false
#    birth: 1997/12/29
#    maps: {k1: v1,k2: v2,k3: v3}
#    lists:
#        - jack
#        - tom
#    dog:
#        name: lele
#        age: 5